name: ag_cli
description: Flutter GetX code generator CLI. Scaffolds modules, components, models, repos, controllers, bindings, and pages.
version: 2.2.0
homepage: https://github.com/kripadevg-code/ag-cli
repository: https://github.com/kripadevg-code/ag-cli
issue_tracker: https://github.com/kripadevg-code/ag-cli/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.5.0
  mason_logger: ^0.3.5
  path: ^1.9.0

dev_dependencies:
  test: ^1.24.0
  lints: ^6.1.0

executables:
  ag: ag
